## Configuration
The following cell is required to load the appropriate modules and ensure they are updated if there are live changes to the code files.

In [1]:
#%autoreload 1
import warnings
from Arena import *
import Tracker
import TwoChoiceTracker
from ExperimentalDesign import *
from Parameters import *

# Suppress all warnings
warnings.filterwarnings('ignore')

## Define the Parameters
Next, create a parameters object that will hold information about the physical arena, camera settings, etc.

The constructor just takes the type of tracker.  For now, we just have a two choice tracker implemented.

This object has several member functions that allow you to automatically set several parameters based on common setups in the lab.

In [2]:
p=Parameters()
p.set_arena_max_values(TrackingType.TWOCHOICETRACKER)

## Read in the data

Next we will read in the data to an Arena object. The format is _Arena(ExperimentName, parameters, data_path="./")_. This will automatically calculate all relevant metrics for the tracking type in question.  

The name of the experiment and predefined parameters object are required.  data_path is optional (if no data directory is specified, it defaults to the current working directory).

The following files must be present in the defined data directory :
* The DTrack experiment file, which is an excel sheet with the name '_ExperimentName.xlsx_'.
* The DTrack data files themselves, which are named '_ExperimentName_Data_1.csv_', '_ExperimentName_Data_2.csv_', etc.
* An experiment file (most of the time, definitely for a TwoChoiceTracker), which is named '_ExperimentName_Design.txt_'.

In [3]:
arena = Arena.Arena('MaxIRSetup',p,data_path='./Data/')

## View Results
There are lots of ways to view the results.  You can get the summary results for all trackers, including treatments, etc.

In [4]:
arena.summarize()
# Like many functions, you can supply a range of minutes to confine the analysis.
arena.summarize(range_minutes=(20,30))
# You can also write the results to the clipboard to paste in excel and/or output to a csv file in the data directory
arena.summarize(write_to_csvfile=True)

,Treatment,Name,TrackingRegion,ObjectID,ObsMinutes,TotalDistance,TotalDistancePerMin,PercSleeping,PercWalking,PercMicro,PercResting,AvgSpeed,StartMinutes,EndMinutes,FinalPI,FinalPercentage,Light,NoLight,Transitions
0,Control,T_0_0,T_0,0,80.024963,14390.052218,179.819543,0.0,0.440124,0.319055,0.240820,2.997236,0.004811,80.029773,0.438894,0.684477,25967,10126,115
1,R2R4,T_1_0,T_1,0,80.024963,8958.863307,111.950859,0.0,0.286027,0.371563,0.342410,1.868732,0.004811,80.029773,-0.242539,0.363287,13782,22608,61
2,Control4,T_10_0,T_10,0,80.024963,10190.696114,127.343966,0.0,0.343253,0.329256,0.327490,2.122131,0.004811,80.029773,-0.541797,0.227561,8633,29049,88
3,R2R4,T_11_0,T_11,0,80.024963,15468.680901,193.298196,0.0,0.606031,0.277486,0.116483,3.221188,0.004811,80.029773,0.045441,0.516989,19613,17908,107
4,Control4,T_12_0,T_12,0,80.024963,18296.753213,228.638072,0.0,0.615705,0.295543,0.088752,3.810714,0.004811,80.029773,0.251934,0.603659,22901,13684,158
5,R2R4,T_13_0,T_13,0,80.024963,28460.408444,355.644132,0.0,0.825131,0.116799,0.058070,5.937576,0.004811,80.029773,0.136735,0.559348,21220,16115,248
6,Control,T_14_0,T_14,0,80.024963,20329.615151,254.040920,0.0,0.663758,0.213064,0.123178,4.239227,0.004811,80.029773,0.142130,0.561958,21319,16013,198
7,R2R4,T_15_0,T_15,0,80.024963,22371.869513,279.561136,0.0,0.732662,0.202125,0.065213,4.670188,0.004811,80.029773,0.115689,0.548963,20826,16507,187
8,Control4,T_16_0,T_16,0,80.024963,10762.418231,134.488263,0.0,0.420091,0.518807,0.061101,2.245739,0.004811,80.029773,0.222189,0.598466,22704,14449,68
9,R2R4,T_17_0,T_17,0,80.024963,17616.496150,220.137511,0.0,0.582097,0.330601,0.087303,3.667773,0.004811,80.029773,0.014680,0.491921,18662,18122,153
10,Control,T_18_0,T_18,0,80.024963,17146.811300,214.268282,0.0,0.593009,0.247964,0.159027,3.572703,0.004811,80.029773,-0.076175,0.460500,17470,20351,163
11,R2R4,T_19_0,T_19,0,80.024963,12378.916210,154.688185,0.0,0.413106,0.304927,0.281967,2.583494,0.004811,80.029773,-0.517336,0.240161,9111,28642,100
12,Control,T_2_0,T_2,0,80.024963,11803.868402,147.502329,0.0,0.425310,0.277829,0.296861,2.454739,0.004811,80.029773,0.578020,0.774389,29378,7856,97
13,Control4,T_20_0,T_20,0,80.024963,14915.495661,186.385537,0.0,0.489443,0.283285,0.227272,3.105416,0.004811,80.029773,0.154271,0.570077,21627,15846,120
14,R2R4,T_21_0,T_21,0,80.024963,6563.790780,82.021791,0.0,0.210243,0.315998,0.473759,1.369988,0.004811,80.029773,-0.772774,0.113319,4299,33540,43
15,Control,T_22_0,T_22,0,80.024963,18992.755740,237.335390,0.0,0.687034,0.229802,0.083164,3.961325,0.004811,80.029773,-0.303828,0.343517,13032,24407,151
16,R2R4,T_23_0,T_23,0,80.024963,9234.613543,115.396662,0.0,0.263226,0.380947,0.355827,1.930270,0.004811,80.029773,-0.629795,0.184068,6983,30742,78
17,Control,T_24_0,T_24,0,80.024963,16347.328516,204.277865,0.0,0.647995,0.286370,0.065635,3.412025,0.004811,80.029773,-0.147125,0.416928,15817,21274,127
18,R2R4,T_25_0,T_25,0,80.024963,12214.180342,152.629629,0.0,0.444843,0.353270,0.201887,2.544558,0.004811,80.029773,0.168657,0.580278,22014,15660,117
19,Control4,T_26_0,T_26,0,80.024963,18455.067703,230.616386,0.0,0.645966,0.219759,0.134275,3.856134,0.004811,80.029773,-0.240774,0.377442,14319,23401,169
20,R2R4,T_27_0,T_27,0,80.024963,14312.978676,178.856424,0.0,0.500751,0.384480,0.114769,2.978432,0.004811,80.029773,-0.245843,0.374226,14197,23453,119
21,Control,T_28_0,T_28,0,80.024963,18032.778308,225.339415,0.0,0.699396,0.222395,0.078209,3.760844,0.004811,80.029773,-0.291788,0.352136,13359,24367,135
22,R2R4,T_29_0,T_29,0,80.024963,16859.754557,210.681192,0.0,0.616838,0.285078,0.098084,3.515264,0.004811,80.029773,-0.278045,0.359807,13650,24164,144
23,R2R4,T_3_0,T_3,0,80.024963,6235.103258,77.914479,0.0,0.229776,0.356565,0.413659,1.300329,0.004811,80.029773,0.744306,0.862061,32704,4794,37
24,Control4,T_30_0,T_30,0,80.024963,27020.611929,337.652290,0.0,0.838205,0.133432,0.028363,5.631272,0.004811,80.029773,-0.253116,0.371985,14112,23677,229
25,R2R4,T_31_0,T_31,0,80.024963,10785.924192,134.781996,0.0,0.349421,0.410470,0.240109,2.246314,0.004811,80.029773,-0.171083,0.412711,15657,22120,88
26,Control,T_32_0,T_32,0,80.024963,30839.277772,385.370723,0.0,0.896592,0.082479,0.020929,6.433482,0.004811,80.029773,-0.054454,0.469383,17807,19858,301
27,R2R4,T_33_0,T_33,0,80.024963,6553.630712,81.894830,0.0,0.271239,0.491104,0.237657,1.364935,0.004811,80.029773,0.048548,0.522920,19838,18001,38
28,Control4,T_34_0,T_34,0,80.024963,15431.053378,192.827998,0.0,0.700925,0.265124,0.033951,3.211540,0.004811,80.029773,-0.088817,0.452961,17184,20534,142
29,R2R4,T_35_0,T_35,0,80.024963,13470.688634,168.331083,0.0,0.424757,0.442233,0.133010,2.808697,0.004811,80.029773,-0.106764,0.446582,16942,20992,118
30,Control,T_4_0,T_4,0,80.024963,16802.579609,209.966728,0.0,0.618868,0.269183,0.111949,3.498990,0.004811,80.029773,0.268684,0.612805,23248,13401,151
31,R2R4,T_5_0,T_5,0,80.024963,10635.292712,132.899690,0.0,0.373277,0.304373,0.322350,2.217004,0.004811,80.029773,0.505472,0.743390,28202,9264,87
32,Control,T_6_0,T_6,0,80.024963,19286.536419,241.006503,0.0,0.712787,0.211008,0.076205,4.024236,0.004811,80.029773,0.307475,0.640641,24304,12873,146
33,R2R4,T_7_0,T_7,0,80.024963,16240.165598,202.938746,0.0,0.591112,0.293197,0.115692,3.378391,0.004811,80.029773,0.160056,0.572765,21729,15733,142
34,Control,T_8_0,T_8,0,80.024963,14299.280091,178.685245,0.0,0.523394,0.251101,0.225505,2.983199,0.004811,80.029773,-0.214090,0.389040,14759,22800,128
35,R2R4,T_9_0,T_9,0,80.024963,12849.494323,160.568576,0.0,0.521681,0.300762,0.177558,2.684867,0.004811,80.029773,-0.057547,0.464929,17638,19792,95

## Plotting
There are lots of cool plotting funtions.  Some are shown below.

In [4]:
arena.summarize(write_to_csvfile=True)

WTF
hi

,Treatment,Name,TrackingRegion,ObjectID,ObsMinutes,TotalDistance,TotalDistancePerMin,PercSleeping,PercWalking,PercMicro,PercResting,AvgSpeed,StartMinutes,EndMinutes,FinalPI,FinalPercentage,Light,NoLight,Transitions
0,Control,T_0_0,T_0,0,80.024963,14390.052218,179.819543,0.0,0.440124,0.319055,0.240820,2.997236,0.004811,80.029773,0.438894,0.684477,25967,10126,115
1,R2R4,T_1_0,T_1,0,80.024963,8958.863307,111.950859,0.0,0.286027,0.371563,0.342410,1.868732,0.004811,80.029773,-0.242539,0.363287,13782,22608,61
2,Control4,T_10_0,T_10,0,80.024963,10190.696114,127.343966,0.0,0.343253,0.329256,0.327490,2.122131,0.004811,80.029773,-0.541797,0.227561,8633,29049,88
3,R2R4,T_11_0,T_11,0,80.024963,15468.680901,193.298196,0.0,0.606031,0.277486,0.116483,3.221188,0.004811,80.029773,0.045441,0.516989,19613,17908,107
4,Control4,T_12_0,T_12,0,80.024963,18296.753213,228.638072,0.0,0.615705,0.295543,0.088752,3.810714,0.004811,80.029773,0.251934,0.603659,22901,13684,158
5,R2R4,T_13_0,T_13,0,80.024963,28460.408444,355.644132,0.0,0.825131,0.116799,0.058070,5.937576,0.004811,80.029773,0.136735,0.559348,21220,16115,248
6,Control,T_14_0,T_14,0,80.024963,20329.615151,254.040920,0.0,0.663758,0.213064,0.123178,4.239227,0.004811,80.029773,0.142130,0.561958,21319,16013,198
7,R2R4,T_15_0,T_15,0,80.024963,22371.869513,279.561136,0.0,0.732662,0.202125,0.065213,4.670188,0.004811,80.029773,0.115689,0.548963,20826,16507,187
8,Control4,T_16_0,T_16,0,80.024963,10762.418231,134.488263,0.0,0.420091,0.518807,0.061101,2.245739,0.004811,80.029773,0.222189,0.598466,22704,14449,68
9,R2R4,T_17_0,T_17,0,80.024963,17616.496150,220.137511,0.0,0.582097,0.330601,0.087303,3.667773,0.004811,80.029773,0.014680,0.491921,18662,18122,153
10,Control,T_18_0,T_18,0,80.024963,17146.811300,214.268282,0.0,0.593009,0.247964,0.159027,3.572703,0.004811,80.029773,-0.076175,0.460500,17470,20351,163
11,R2R4,T_19_0,T_19,0,80.024963,12378.916210,154.688185,0.0,0.413106,0.304927,0.281967,2.583494,0.004811,80.029773,-0.517336,0.240161,9111,28642,100
12,Control,T_2_0,T_2,0,80.024963,11803.868402,147.502329,0.0,0.425310,0.277829,0.296861,2.454739,0.004811,80.029773,0.578020,0.774389,29378,7856,97
13,Control4,T_20_0,T_20,0,80.024963,14915.495661,186.385537,0.0,0.489443,0.283285,0.227272,3.105416,0.004811,80.029773,0.154271,0.570077,21627,15846,120
14,R2R4,T_21_0,T_21,0,80.024963,6563.790780,82.021791,0.0,0.210243,0.315998,0.473759,1.369988,0.004811,80.029773,-0.772774,0.113319,4299,33540,43
15,Control,T_22_0,T_22,0,80.024963,18992.755740,237.335390,0.0,0.687034,0.229802,0.083164,3.961325,0.004811,80.029773,-0.303828,0.343517,13032,24407,151
16,R2R4,T_23_0,T_23,0,80.024963,9234.613543,115.396662,0.0,0.263226,0.380947,0.355827,1.930270,0.004811,80.029773,-0.629795,0.184068,6983,30742,78
17,Control,T_24_0,T_24,0,80.024963,16347.328516,204.277865,0.0,0.647995,0.286370,0.065635,3.412025,0.004811,80.029773,-0.147125,0.416928,15817,21274,127
18,R2R4,T_25_0,T_25,0,80.024963,12214.180342,152.629629,0.0,0.444843,0.353270,0.201887,2.544558,0.004811,80.029773,0.168657,0.580278,22014,15660,117
19,Control4,T_26_0,T_26,0,80.024963,18455.067703,230.616386,0.0,0.645966,0.219759,0.134275,3.856134,0.004811,80.029773,-0.240774,0.377442,14319,23401,169
20,R2R4,T_27_0,T_27,0,80.024963,14312.978676,178.856424,0.0,0.500751,0.384480,0.114769,2.978432,0.004811,80.029773,-0.245843,0.374226,14197,23453,119
21,Control,T_28_0,T_28,0,80.024963,18032.778308,225.339415,0.0,0.699396,0.222395,0.078209,3.760844,0.004811,80.029773,-0.291788,0.352136,13359,24367,135
22,R2R4,T_29_0,T_29,0,80.024963,16859.754557,210.681192,0.0,0.616838,0.285078,0.098084,3.515264,0.004811,80.029773,-0.278045,0.359807,13650,24164,144
23,R2R4,T_3_0,T_3,0,80.024963,6235.103258,77.914479,0.0,0.229776,0.356565,0.413659,1.300329,0.004811,80.029773,0.744306,0.862061,32704,4794,37
24,Control4,T_30_0,T_30,0,80.024963,27020.611929,337.652290,0.0,0.838205,0.133432,0.028363,5.631272,0.004811,80.029773,-0.253116,0.371985,14112,23677,229
25,R2R4,T_31_0,T_31,0,80.024963,10785.924192,134.781996,0.0,0.349421,0.410470,0.240109,2.246314,0.004811,80.029773,-0.171083,0.412711,15657,22120,88
26,Control,T_32_0,T_32,0,80.024963,30839.277772,385.370723,0.0,0.896592,0.082479,0.020929,6.433482,0.004811,80.029773,-0.054454,0.469383,17807,19858,301
27,R2R4,T_33_0,T_33,0,80.024963,6553.630712,81.894830,0.0,0.271239,0.491104,0.237657,1.364935,0.004811,80.029773,0.048548,0.522920,19838,18001,38
28,Control4,T_34_0,T_34,0,80.024963,15431.053378,192.827998,0.0,0.700925,0.265124,0.033951,3.211540,0.004811,80.029773,-0.088817,0.452961,17184,20534,142
29,R2R4,T_35_0,T_35,0,80.024963,13470.688634,168.331083,0.0,0.424757,0.442233,0.133010,2.808697,0.004811,80.029773,-0.106764,0.446582,16942,20992,118
30,Control,T_4_0,T_4,0,80.024963,16802.579609,209.966728,0.0,0.618868,0.269183,0.111949,3.498990,0.004811,80.029773,0.268684,0.612805,23248,13401,151
31,R2R4,T_5_0,T_5,0,80.024963,10635.292712,132.899690,0.0,0.373277,0.304373,0.322350,2.217004,0.004811,80.029773,0.505472,0.743390,28202,9264,87
32,Control,T_6_0,T_6,0,80.024963,19286.536419,241.006503,0.0,0.712787,0.211008,0.076205,4.024236,0.004811,80.029773,0.307475,0.640641,24304,12873,146
33,R2R4,T_7_0,T_7,0,80.024963,16240.165598,202.938746,0.0,0.591112,0.293197,0.115692,3.378391,0.004811,80.029773,0.160056,0.572765,21729,15733,142
34,Control,T_8_0,T_8,0,80.024963,14299.280091,178.685245,0.0,0.523394,0.251101,0.225505,2.983199,0.004811,80.029773,-0.214090,0.389040,14759,22800,128
35,R2R4,T_9_0,T_9,0,80.024963,12849.494323,160.568576,0.0,0.521681,0.300762,0.177558,2.684867,0.004811,80.029773,-0.057547,0.464929,17638,19792,95